name: sandbox
description: A sandbox application where the Very Good Ranch components are showcased and developed in isolation
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dashbook: ^0.1.8
  flame: ^1.1.1  
  flutter:
    sdk: flutter
  ranch_components:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
