version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/ranch_components"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/ranch_flame"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/ranch_sounds"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/ranch_ui"
    schedule:
      interval: "daily"
