name: ranch_sounds
description: Package containing sounds typical of any Unicorn ranch
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  audioplayers: ^1.0.1
  flame_audio: ^1.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: 3.0.2


flutter:
  assets:
    - assets/music/
