name: ranch_flame
description: Custom additions for Flame for the Very Good Ranch game.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flame: ^1.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_test: ^1.4.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0