name: ranch_components
description: Package with the game components for the Very Good Ranch game.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flame: ^1.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_test: ^1.7.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  generate: true
  assets:
    - assets/background/
    - assets/food/
    - assets/animations/

flutter_gen:
  line_length: 80
  assets:
    package_parameter_enabled: true
