name: ranch_sounds

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - "packages/ranch_sounds/**"
      - ".github/workflows/ranch_sounds.yaml"

  pull_request:
    paths:
      - "packages/ranch_sounds/**"
      - ".github/workflows/ranch_sounds.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.3.2
      working_directory: packages/ranch_sounds
      coverage_excludes: "lib/gen/*.dart"
