name: ranch_ui

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - "packages/ranch_ui/**"
      - ".github/workflows/ranch_ui.yaml"

  pull_request:
    paths:
      - "packages/ranch_ui/**"
      - ".github/workflows/ranch_ui.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.0.5
      working_directory: packages/ranch_ui
      coverage_excludes: "lib/gen/*.dart"
